#=========================== Filebeat inputs =============================  
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/app/app.log

  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: msg

  tags: ["fastify-app", "development"]
  fields:
    service: "fastify-api1"
    environment: "development"

#==================== Elasticsearch output =====================
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"            # usuário com permissão no Elasticsearch
  password: "12345678"           # senha configurada
  timeout: 90s
  max_retries: 3

#==================== Kibana ===================================
setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "12345678"

#==================== Template management =====================
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

#==================== Logging ===================================
logging.level: info
