services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastify_app_service
    ports:
      - "3000:3000"
    volumes:
      - app_logs:/app/logs
    environment:
      NODE_ENV: development
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic_monitoring_net
    restart: unless-stopped
    command: sh -c "sleep 30 && node src/api1.js"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch_service
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -u elastic:12345678 -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - elastic_monitoring_net
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana_service
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elastic_monitoring_net
    restart: unless-stopped

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.13.4
    container_name: apm_server
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8200:8200"
    environment:
      - output.elasticsearch.hosts=http://elasticsearch:9200
      - output.elasticsearch.username=elastic
      - output.elasticsearch.password=12345678
      - apm-server.host=0.0.0.0:8200
      - apm-server.register.ingest.pipeline.enabled=true
      - apm-server.kibana.enabled=true
      - apm-server.kibana.host=http://kibana:5601
      - apm-server.kibana.username=elastic
      - apm-server.kibana.password=12345678
    networks:
      - elastic_monitoring_net
    restart: unless-stopped

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.4
    container_name: filebeat_service
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - app_logs:/var/log/app:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
      app:
        condition: service_started
    networks:
      - elastic_monitoring_net
    command: filebeat -e -strict.perms=false
    restart: unless-stopped

volumes:
  es_data:
    driver: local
  app_logs:
    driver: local

networks:
  elastic_monitoring_net:
    driver: bridge
